// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function FormatContent(arg1:string,arg2:string):Promise<main.ProcessResult>;

export function OpenFile(arg1:string):Promise<main.OpenFileResult>;

export function ValidateContent(arg1:string,arg2:string):Promise<main.ProcessResult>;
